_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[-0.7485454  -0.70058906  1.1468292  ... -0.7070714   1.4141783
          -0.7070715 ]
         [-0.34053072 -0.80812216 -0.54218507 ...  1.4141781  -0.7070715
          -0.7070715 ]
         [ 0.6665855   0.7184576   0.25367758 ... -0.7070714  -0.7070715
           1.4141783 ]
         [-0.79784834  0.10291109 -1.0608054  ...  1.4141781  -0.7070715
          -0.7070715 ]
         [ 0.34873593  0.22440824 -0.6730875  ... -0.7070714   1.4141783
          -0.7070715 ]
         [ 0.8864999   0.4771281   0.87556136 ... -0.7070714  -0.7070715
           1.4141783 ]]
_last_original_obs:
    value: |-
        [[ 1.3926651e+00  9.9229956e-01  7.4523184e-03 ...  0.0000000e+00
           1.0000000e+00  0.0000000e+00]
         [ 1.3965087e+00  9.9154496e-01 -4.5497301e-03 ...  1.0000000e+00
           0.0000000e+00  0.0000000e+00]
         [ 1.4059958e+00  1.0022575e+00  1.1056288e-03 ...  0.0000000e+00
           0.0000000e+00  1.0000000e+00]
         [ 1.3922007e+00  9.9793798e-01 -8.2350196e-03 ...  1.0000000e+00
           0.0000000e+00  0.0000000e+00]
         [ 1.4030017e+00  9.9879056e-01 -5.4799160e-03 ...  0.0000000e+00
           1.0000000e+00  0.0000000e+00]
         [ 1.4080675e+00  1.0005640e+00  5.5247028e-03 ...  0.0000000e+00
           0.0000000e+00  1.0000000e+00]]
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7bf451b48bd0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 3000000
_vec_normalize_env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x7bf461fcbd50>
_wandb:
    value:
        cli_version: 0.27.0
        e:
            09fm542524ef5cu0h3907wo83qd2vjj3:
                args:
                    - --timesteps
                    - "3_000_000"
                    - --n_envs
                    - "6"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "51835101184"
                        used: "29869166592"
                email: hoshuhan@gmail.com
                executable: /home/hoshuhan/miniconda3/envs/dancing-agent/bin/python
                git:
                    commit: 076fdf1cafdcb23d1ef4850ee7fea3809a338864
                    remote: https://github.com/HOSH19/Dancing_Agent.git
                host: dancing
                memory:
                    total: "33651986432"
                os: Linux-6.8.0-1058-gcp-x86_64-with-glibc2.35
                program: /home/hoshuhan/Dancing_Agent/train.py
                python: CPython 3.11.15
                root: /home/hoshuhan/Dancing_Agent
                startedAt: "2026-05-19T16:05:57.883621Z"
                writerId: 09fm542524ef5cu0h3907wo83qd2vjj3
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
                - 22
            "4": 3.11.15
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Box(-0.4, 0.4, (17,), float32)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x7bf461fcbd50>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
features_dir:
    value: features
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
genre:
    value: null
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 6
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: |-
        Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf   0.   0.
           0.   0.   0.   0.   0.   0.], [inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf  1.  1.  1.  1.  1.  1.  1.  1.], (356,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=356, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=356, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=17, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7bf461f914d0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
save_dir:
    value: checkpoints
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1779206767554133200
target_kl:
    value: None
tensorboard_log:
    value: None
timesteps:
    value: 3000000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
video_dir:
    value: videos/training
video_freq:
    value: 500000
