_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        [[-0.50661796 -0.35646915  0.43877697 ... -0.57730216  1.7319641
          -0.99992496]
         [ 0.9328937   0.22628616  0.32163113 ...  1.7319641  -0.57730216
          -0.99992496]
         [-0.34888533  0.7900937   0.08673322 ... -0.57730216 -0.57730216
           0.99997497]
         [-0.06392811 -0.64816    -0.8471894  ... -0.57730216 -0.57730216
           0.99997497]]
_last_original_obs:
    value: |-
        [[ 1.3942709e+00  9.9266922e-01 -2.4598185e-04 ...  0.0000000e+00
           1.0000000e+00  0.0000000e+00]
         [ 1.4092104e+00  9.9760419e-01 -9.2485588e-04 ...  1.0000000e+00
           0.0000000e+00  0.0000000e+00]
         [ 1.3959079e+00  1.0023787e+00 -2.2861173e-03 ...  0.0000000e+00
           0.0000000e+00  1.0000000e+00]
         [ 1.3988652e+00  9.9019909e-01 -7.6983101e-03 ...  0.0000000e+00
           0.0000000e+00  1.0000000e+00]]
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x78b1c6267450>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1500000
_vec_normalize_env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x78b1d3587010>
_wandb:
    value:
        cli_version: 0.27.0
        e:
            spg40dj46vx9n52tt5sbnfmpvdu8af6k:
                args:
                    - --timesteps
                    - "1_500_000"
                    - --n_envs
                    - "4"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "51835101184"
                        used: "30180544512"
                email: hoshuhan@gmail.com
                executable: /home/hoshuhan/miniconda3/envs/dancing-agent/bin/python
                git:
                    commit: 076fdf1cafdcb23d1ef4850ee7fea3809a338864
                    remote: https://github.com/HOSH19/Dancing_Agent.git
                host: dancing
                memory:
                    total: "33651986432"
                os: Linux-6.8.0-1058-gcp-x86_64-with-glibc2.35
                program: /home/hoshuhan/Dancing_Agent/train.py
                python: CPython 3.11.15
                root: /home/hoshuhan/Dancing_Agent
                startedAt: "2026-05-19T22:06:46.546341Z"
                writerId: spg40dj46vx9n52tt5sbnfmpvdu8af6k
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 3
                - 16
                - 22
                - 61
            "4": 3.11.15
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Box(-0.4, 0.4, (17,), float32)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x78b1d3587010>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
eval_freq:
    value: 50000
features_dir:
    value: features
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
genre:
    value: null
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: |-
        Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
         -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf   0.   0.
           0.   0.   0.   0.   0.   0.], [inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
         inf inf inf inf inf inf  1.  1.  1.  1.  1.  1.  1.  1.], (356,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=356, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=356, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=17, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x78b1d35ac290>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
save_dir:
    value: checkpoints
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1779228414613592579
target_kl:
    value: None
tensorboard_log:
    value: None
timesteps:
    value: 1500000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
video_dir:
    value: videos/training
video_freq:
    value: 500000
